### ISSUE TITLE
DietPi RPi Kernel | Patch for native DSD

### ISSUE THREAD

**Issue by Fourdee** [MichaIng/DietPi#1021]
> https://github.com/lintweaker/xmos-native-dsd

**Comment by Fourdee** [comment]
Patches as they exist at the moment, do not work with RPi 4.9 kernel, most of them fail. Tried to compile anyway, fails with:
```
sound/usb/quirks.c: In function ‘snd_usb_apply_boot_quirk’:
sound/usb/quirks.c:1033:9: error: ‘chip’ undeclared (first use in this function)
  switch(chip->usb_id) {
         ^
sound/usb/quirks.c:1033:9: note: each undeclared identifier is reported only once for each function it appears in
sound/usb/quirks.c:1037:7: error: ‘fp’ undeclared (first use in this function)
   if (fp->altsetting == 2)
       ^
sound/usb/quirks.c:1038:4: warning: overflow in implicit constant conversion [-Woverflow]
    return SNDRV_PCM_FMTBIT_DSD_U32_LE;
    ^
sound/usb/quirks.c:1044:4: warning: overflow in implicit constant conversion [-Woverflow]
    return SNDRV_PCM_FMTBIT_DSD_U32_LE;
    ^
sound/usb/quirks.c:1055:4: warning: overflow in implicit constant conversion [-Woverflow]
    return SNDRV_PCM_FMTBIT_DSD_U32_BE;
    ^
sound/usb/quirks.c: At top level:
sound/usb/quirks.c:1264:5: error: redefinition of ‘snd_usb_select_mode_quirk’
 int snd_usb_select_mode_quirk(struct snd_usb_substream *subs,
     ^
sound/usb/quirks.c:1210:5: note: previous definition of ‘snd_usb_select_mode_quirk’ was here
 int snd_usb_select_mode_quirk(struct snd_usb_substream *subs,
     ^
  DTCO    arch/arm/boot/dts/overlays/hifiberry-dac.dtbo
sound/usb/quirks.c: In function ‘snd_usb_interface_dsd_format_quirks’:
sound/usb/quirks.c:1467:2: error: duplicate case value
  case USB_ID(0x16d0, 0x071a): /* Amanero Combo384 */
  ^
sound/usb/quirks.c:1461:2: error: previously used here
  case USB_ID(0x16d0, 0x071a): /* Amanero Combo384 */
  ^
scripts/Makefile.build:293: recipe for target 'sound/usb/quirks.o' failed
```

**Comment by Fourdee** [comment]
Marking as closed for now, unable to dedicate time for this.
